name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Switch to Xcode 11.3.1
        run: sudo xcode-select --switch /Applications/Xcode_11.3.1.app

      - name: Builds Package
        run: swift build --target Coordinator -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
    
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: .build/
