# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Switch to Xcode 11.3.1
        run: sudo xcode-select --switch /Applications/Xcode_11.3.1.app

      - name: Builds Package
        run: swift build --target Coordinator -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
    
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: .build/
  test:
    runs-on: macos-latest
    needs: [ build ]
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Switch to Xcode 11.3.1
        run: sudo xcode-select --switch /Applications/Xcode_11.3.1.app

      - name: Generate .xcodeproj
        run: swift package generate-xcodeproj
        
      - uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: build

      - name: Run tests
        run: xcodebuild test -scheme Coordinator-Package -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4'
